# Site settings
title: "Matt Born"
email: mattborn@users.noreply.github.com
description: "Personal portfolio site and blog."
baseurl: ""
url: "http://mattborn.com"

# Build settings
markdown: kramdown
permalink: :title