# Site settings
title: Matt Born
email: me+code@mattborn.com
description: "Hey, my name’s Matt and I live in Chicago with my wife Megan & daughter Maely. I started creating for the web in 1999 and I never stopped."
baseurl: ""
url: "http://mattborn.com"
twitter_username: matthewcyan
github_username: mattborn

# Build settings
markdown: kramdown
